In [ ]:
import numpy as np

np.random.seed(42)

A = np.random.normal(50, 12, (1000, 5))

print("Shape:", A.shape)
print("Dtype:", A.dtype)
print("Memory:", A.nbytes, "bytes")

A = A.astype(np.float32)

print("New dtype:", A.dtype)
print("New memory:", A.nbytes, "bytes")

Shape: (1000, 5)
Dtype: float64
Memory: 40000 bytes
New dtype: float32
New memory: 20000 bytes


In [ ]:
mean = A.mean(axis=0)
std = A.std(axis=0)

Z = (A - mean) / std

print("Mean of columns:")
print(Z.mean(axis=0))

print("Standard deviation of columns:")
print(Z.std(axis=0))

Mean of columns:
[-3.7474558e-06  1.9576551e-06  1.8019676e-06 -3.3002495e-06
  4.5824052e-07]
Standard deviation of columns:
[0.9999991  1.0000001  0.99999976 1.         1.        ]


In [ ]:
import numpy as np

def minmax(X, axis):
    minimum = X.min(axis=axis, keepdims=True)
    maximum = X.max(axis=axis, keepdims=True)
    return (X - minimum) / (maximum - minimum)

# Define X using a slice of A as done in the later cells
X = A[:200]

result0 = minmax(X, 0)

print("Axis 0 minimum:", result0.min(axis=0))
print("Axis 0 maximum:", result0.max(axis=0))
result1 = minmax(X, 1)

print("Axis 1 minimum:", result1.min(axis=1))
print("Axis 1 maximum:", result1.max(axis=1))

Axis 0 minimum: [0. 0. 0. 0. 0.]
Axis 0 maximum: [1. 1. 1. 1. 1.]
Axis 1 minimum: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.
 0. 0. 0. 0. 0. 0. 0. 0.]
Axis 1 maximum: [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.


In [ ]:
np.random.seed(42)

mask = np.random.random(A.shape) < 0.05

A[mask] = np.nan

column_means = np.nanmean(A, axis=0)

for i in range(A.shape[1]):
    missing = np.isnan(A[:, i])
    A[missing, i] = column_means[i]

print(np.isnan(A).sum() == 0)

True


In [15]:
mean = A.mean(axis=0)

std = A.std(axis=0)

outliers = np.abs(A - mean) > 3 * std

median = np.median(A, axis=0)

for i in range(A.shape[1]):
    A[outliers[:, i], i] = median[i]

print("Values replaced per column:", outliers.sum(axis=0))
print("Total values replaced:", outliers.sum())

Values replaced per column: [4 1 5 3 5]
Total values replaced: 18


In [ ]:
import numpy as np

X = A[:200]

diff = X[:, np.newaxis, :] - X[np.newaxis, :, :]
D = np.sqrt(np.sum(diff ** 2, axis=2))

print("Distance matrix shape:", D.shape)
print("Diagonal is zero:", np.allclose(np.diag(D), 0))
print("Matrix is symmetric:", np.allclose(D, D.T))

Distance matrix shape: (200, 200)
Diagonal is zero: True
Matrix is symmetric: True


In [ ]:
import numpy as np

distance_matrix_copy = D.copy()
np.fill_diagonal(distance_matrix_copy, np.inf)

nearest_5_indices = np.argpartition(distance_matrix_copy, kth=5, axis=1)[:, :5]

print("Shape:", nearest_5_indices.shape)
print("Sample of first 5 rows nearest neighbors:\n", nearest_5_indices[:5])

Shape: (200, 5)
Sample of first 5 rows nearest neighbors:
 [[180 179 116 182 120]
 [199 114  17  70  31]
 [  3 158  99 132 145]
 [132   2  99 145   5]
 [160 158 143 102  43]]


In [16]:
import numpy as np

np.random.seed(42)
numbers = np.random.randint(0, 100, size=1_000_000)

print("--- NumPy Bincount Timing ---")
%time counts_numpy = np.bincount(numbers)
print("First 10 counts (NumPy):", counts_numpy[:10])

print("\n--- Pure Python Loop Timing ---")
numbers_list = numbers.tolist()

counts_python = [0] * 100

def run_python_loop():
    for num in numbers_list:
        counts_python[num] += 1

%time run_python_loop()

print("First 10 counts (Python):", counts_python[:10])
print("Results match:", list(counts_numpy) == counts_python)

--- NumPy Bincount Timing ---
CPU times: user 2.76 ms, sys: 0 ns, total: 2.76 ms
Wall time: 2.39 ms
First 10 counts (NumPy): [ 9995 10049 10103  9927 10130 10010  9956  9968 10074 10028]

--- Pure Python Loop Timing ---
CPU times: user 79.2 ms, sys: 34 µs, total: 79.2 ms
Wall time: 80.3 ms
First 10 counts (Python): [9995, 10049, 10103, 9927, 10130, 10010, 9956, 9968, 10074, 10028]
Results match: True


In [ ]:
import numpy as np
import pandas as pd

from numpy.lib.stride_tricks import sliding_window_view

x = np.random.randn(10000)

windows = sliding_window_view(x, 10)

print("Shape:", windows.shape)

numpy_means = windows.mean(axis=1)

pandas_means = pd.Series(x).rolling(10).mean().dropna().to_numpy()

print("Results are same:", np.allclose(numpy_means, pandas_means))

Shape: (9991, 10)
Results are same: True


In [ ]:
import numpy as np

X = np.random.randn(12, 8)

X = X.reshape(4, 3, 8)

result = X.mean(axis=1)

print(result.shape)

(4, 8)


In [17]:
import numpy as np

np.save("clean.npy", A)

loaded_A = np.load("clean.npy")

assert np.array_equal(loaded_A, A)

print("Array saved, loaded, and verified successfully.")

Array saved, loaded, and verified successfully.
